### ISSUE TITLE
How dose the MANO-based hand model pick up the object?

### ISSUE THREAD

**Issue by FredTrumpSenior** [NVlabs/handover-sim2real#7]
Hello, thanks for your great work!

The handover demonstration is amazing, and I'm also curious how the objects are picked up from the table by the MANO-based hand model, as a universal grasping method of the human hand is even harder than that of a parallel gripper in my understanding.

Can you explain, thank.

**Comment by sammychristen** [comment]
Hi, 

Thanks for your interest in our work.

The generation of the human hand-object motion is explained in detail in the [Handover-Sim Paper](https://handover-sim.github.io/assets/chao_icra2022.pdf) (section III). In short, rather than relying on the human hand to physically move the object, we augment the object models by adding additional actuators to their base such that their 6D pose can be directly actuated by controllers in simulation. The hand-object motions are then "replayed" using data from DexYCB (with collisions between hand and object being disabled).

Learning a universal grasping method is indeed challenging. In our [latest work](https://eth-ait.github.io/synthetic-handovers), we scale to many more objects for handovers (than available in the DexYCB dataset) by learning a general RL-based dexterous grasping policy.

**Comment by FredTrumpSenior** [comment]
Thanks for your answer! It helps a lot!
